name: Collect AQI Data

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pandas

    - name: Run collector
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        POWERBI_PUSH_URL_DELHI: ${{ secrets.POWERBI_PUSH_URL_DELHI }}
        POWERBI_PUSH_URL_MUMBAI: ${{ secrets.POWERBI_PUSH_URL_MUMBAI }}
        POWERBI_PUSH_URL_CHENNAI: ${{ secrets.POWERBI_PUSH_URL_CHENNAI }}
        POWERBI_PUSH_URL_KOLKATA: ${{ secrets.POWERBI_PUSH_URL_KOLKATA }}
        POWERBI_PUSH_URL_BENGALURU: ${{ secrets.POWERBI_PUSH_URL_BENGALURU }}
        POWERBI_PUSH_URL_AHMEDABAD: ${{ secrets.POWERBI_PUSH_URL_AHMEDABAD }}
        POWERBI_PUSH_URL_LUCKNOW: ${{ secrets.POWERBI_PUSH_URL_LUCKNOW }}
        POWERBI_PUSH_URL_HYDERABAD: ${{ secrets.POWERBI_PUSH_URL_HYDERABAD }}
        POWERBI_PUSH_URL_JAIPUR: ${{ secrets.POWERBI_PUSH_URL_JAIPUR }}
        POWERBI_PUSH_URL_PATNA: ${{ secrets.POWERBI_PUSH_URL_PATNA }}
        POWERBI_PUSH_URL_ALL: ${{ secrets.POWERBI_PUSH_URL_ALL }}
      run: python aqi_collector.py

    - name: Prepare docs
      run: |
        mkdir -p docs/data
        cp data/aqi_data.csv docs/data/

    - name: Commit and push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
        git push
