name: Collect AQI Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pandas

    - name: Run collector
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: python aqi_collector.py

    - name: Prepare docs
      run: |
        mkdir -p docs/data
        cp data/aqi_data.csv docs/data/
        [ -f docs/index.html ] || cp default_index.html docs/index.html

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Auto-update data and docs" || echo "No changes to commit"
        git push
